### ISSUE TITLE
make a small note that port 8080 deviceURL is also available

### ISSUE THREAD

**Issue by shaunmulligan** [resin-io/docs#298]
We should let users know that port 8080 is also available on the deviceURL, but is only HTTP not HTTPS.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_kis)

**Comment by emirotin** [comment]
We planned to delete it eventually, that’s why we’ve hidden the mentions of it in the UI and everywhere.

On Wed, Aug 17, 2016 at 5:30 PM Shaun Mulligan

<
mailto:Shaun Mulligan <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

We should let users know that port 8080 is also available on the deviceURL, but is only HTTP not HTTPS.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/resin-io/docs/issues/298
, or
